apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: torch-transformer
spec:
  predictor:
    triton:
      storageUri: gs://kfserving-examples/models/torchscript
      runtimeVersion: 20.10-py3
      # networkProtocol: grpc
      env:
      - name: OMP_NUM_THREADS
        value: "1"
      args:
      - --log-verbose=1
      ports:
        - name: h2c
          protocol: TCP
          containerPort: 9000
  transformer:
    containers:
    # - image: kfserving/image-transformer-v2:latest
    - image: cxu138/kserve_test:latest
      name: kfserving-container
      command:
      - "python"
      - "-m"
      - "image_transformer_v2"
      args:
      - --model_name
      - cifar10
      - --protocol
      - v2
      - --networkProtocol
      - grpc
